[log]
  level = "ERROR"

[providers.docker]
  exposedByDefault = false
  endpoint = "unix:///var/run/docker.sock"
  network = "traefik"

[api]
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.default.acme]
    email = "kingr4@protonmail.ch"
    storage = "acme.json"
  [certificatesResolvers.default.acme.httpChallenge]
    entryPoint = "web"

[http]
  [http.routers]
    [http.routers.my-api]
      rule = "Host(`traefik.r4.ie`)"
      service = "api@internal"
      middlewares = ["auth"]
      
  [http.middlewares]    
    [http.middlewares.auth.basicAuth]
      users = [
        "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/",
      ]